### ISSUE TITLE
[bug] Layout Issue for Dashboard

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_web#124]
Make sure layout is rendering correctly
<img width="1440" alt="Screenshot 2020-01-17 at 3 31 20 PM" src="https://user-images.githubusercontent.com/588467/72603221-9e036680-393e-11ea-8707-0e0178767780.png">

**Comment by sidharthshah** [comment]
@hkacha any updates on this task?

**Comment by Shivani-Padhye** [comment]
this issue is occurring on the Ipad Safari web application, the sidebar is not showing the proper category names in portrait mode. similarly, the UI of the graphs is not proper or messy in mobile web app.
![74211](https://user-images.githubusercontent.com/57176686/76824179-5add4b00-683c-11ea-9eee-88b97d0a2adb.jpg)
